import Head from "next/head"
import React from "react"
import Navbar from "../navbar"

interface Props {
  children: JSX.Element
}

const Layout: React.FC<Props> = ({ children }) => {
  return (
    <div className="flex h-screen w-screen select-none bg-stone-50 text-slate-600">
      <Head>
        <title>B3nch</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, user-scalable=no" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="flex flex-1 pt-14">{children}</div>
    </div>
  )
}

export default Layout
